import 'dart:convert';
import '../models/surah.dart';
import '../models/ayat.dart';

/// Quran Local Data - All Quran data embedded in the app
/// This data is from equran.id API and includes:
/// - 114 Surahs with complete information
/// - All ayat data loaded from quran_data.json
class QuranData {
  // All surahs data - Will be populated by generator script or from JSON
  static final List<Surah> allSurahs = [
    // Sample data - will be replaced by generated data from Python script
    Surah(nomor: 1, nama: 'الفاتحة', namaLatin: 'Al-Fatihah', jumlahAyat: 7),
    Surah(nomor: 2, nama: 'البقرة', namaLatin: 'Al-Baqarah', jumlahAyat: 286),
    // ... (full list generated by tools/generate_quran_data.py)
  ];

  // Map to store ayat data for each surah
  static final Map<int, List<Ayat>> _ayatCache = {};
  static bool _initialized = false;

  /// Get all ayat for a specific surah
  static List<Ayat> getAyatBySurah(int surahNumber) {
    if (_ayatCache.containsKey(surahNumber)) {
      return _ayatCache[surahNumber]!;
    }
    return [];
  }

  /// Check if data is initialized
  static bool get isInitialized => _initialized;

  /// Initialize ayat data (call once on app startup)
  static Future<void> initializeAyatData(String jsonString) async {
    if (_initialized) return;

    try {
      final jsonData = jsonDecode(jsonString) as Map<String, dynamic>;
      final surahs = jsonData['surahs'] as List<dynamic>;

      for (var surah in surahs) {
        final surahNum = surah['nomor'] as int;
        final ayatList = <Ayat>[];

        for (var ayat in surah['ayat'] as List<dynamic>) {
          ayatList.add(Ayat(
            nomor: ayat['nomorAyat'] as int,
            arab: ayat['teksArab'] as String,
            latin: ayat['teksLatin'] as String,
            indo: ayat['teksIndonesia'] as String,
          ));
        }

        _ayatCache[surahNum] = ayatList;
      }

      _initialized = true;
    } catch (e) {
      // Silent error handling - data will be empty until generator script is run
    }
  }
}
